require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: disable

inherit_from:
  - .rubocop_rails.yml
  - .rubocop_rspec.yml

# https://github.com/rubocop/rubocop/blob/v1.31.1/config/default.yml

Style/RedundantFetchBlock:
  Enabled: true
  Safe: true
  SafeForConstants: true

Style/GlobalStdStream:
  StyleGuide: '#global-stdout'
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
  SafeAutoCorrect: true

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case
